api:
  host: "localhost"
  port: "8081"
  protocol: "HTTP"
  timeout: "30000"
  
salesforce:
  userName:  "manisha.deshmukh@caeliusconsulting.com"
  password: "change it"
  authURL: "https://caelius6-dev-ed.my.salesforce.com/services/Soap/u/54.0"
  token: "XsBhvEpSRDMUKWHuTmFLZM6v"  